### ISSUE TITLE
使用二进制在windows平台下报错

### ISSUE THREAD

**Issue by chenspnjupt** [Clouder0/AnkiSiyuan#12]
D:\GreenSoftware\ankisiyuan>ankisiyuan.exe
Warning: Config File config.toml doesn't exist!
Api Token:
Last Sync:20210728120950
Now Sync: 20230505070230
Traceback (most recent call last):
  File "C:\Users\chensp\AppData\Local\Temp\ONEFIL~1\toml\decoder.py", line 511, in loads
  File "C:\Users\chensp\AppData\Local\Temp\ONEFIL~1\toml\decoder.py", line 778, in load_line
  File "C:\Users\chensp\AppData\Local\Temp\ONEFIL~1\toml\decoder.py", line 880, in load_value
  File "C:\Users\chensp\AppData\Local\Temp\ONEFIL~1\toml\decoder.py", line 1026, in load_array
  File "C:\Users\chensp\AppData\Local\Temp\ONEFIL~1\toml\decoder.py", line 849, in load_value
ValueError: Found tokens after a closed string. Invalid TOML.

During handling of the above exception, another exception occurred:

**Comment by Clouder0** [comment]
这个是解析配置时出错了，看看在思源中的属性设置是否正确呢？
